In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.random.randint(0, 500, 5000).reshape(1000, 5)

In [3]:
X.shape

(1000, 5)

In [4]:
cov_mat = np.cov(X, rowvar = False)

In [5]:
cov_mat.shape

(5, 5)

In [6]:
eigen_value, eigen_vect = np.linalg.eigh(cov_mat)

In [7]:
eigen_value

array([19343.69958969, 20200.85778102, 20844.70138112, 21374.25352349,
       23300.28189685])

In [8]:
eigen_vect

array([[ 0.67852394, -0.04150401,  0.08718039,  0.63789115, -0.35125082],
       [ 0.38361298, -0.58148357, -0.43909188, -0.51590115, -0.23614034],
       [ 0.27324662,  0.37153836,  0.59093724, -0.5500008 , -0.36822253],
       [ 0.42506043,  0.64164511, -0.5064041 , -0.14183883,  0.36201081],
       [ 0.37027861, -0.3322726 ,  0.44039298, -0.06573996,  0.74446017]])

In [9]:
sorted_index = np.argsort(eigen_value)
print(sorted_index)

[0 1 2 3 4]


In [10]:
sorted_index = sorted(sorted_index, reverse = True)
print(sorted_index)

[4, 3, 2, 1, 0]


In [11]:
eigen_value = eigen_value[sorted_index]
eigen_vect = eigen_vect[sorted_index]

In [14]:
eigen_value

array([23300.28189685, 21374.25352349, 20844.70138112, 20200.85778102,
       19343.69958969])

In [13]:
eigen_vect

array([[ 0.37027861, -0.3322726 ,  0.44039298, -0.06573996,  0.74446017],
       [ 0.42506043,  0.64164511, -0.5064041 , -0.14183883,  0.36201081],
       [ 0.27324662,  0.37153836,  0.59093724, -0.5500008 , -0.36822253],
       [ 0.38361298, -0.58148357, -0.43909188, -0.51590115, -0.23614034],
       [ 0.67852394, -0.04150401,  0.08718039,  0.63789115, -0.35125082]])

In [15]:
n_comp = 2

eigen_vect = eigen_vect[:n_comp, :]
print(eigen_vect.shape)

(2, 5)


In [16]:
X_pca = np.dot(eigen_vect, X.T)

In [18]:
X_pca = X_pca.T

In [19]:
X_pca.shape

(1000, 2)